import type { Category, Product, Market, User, Order } from "./types"

export const mockMarket: Market = {
  id: "1",
  name: "Mercado São Jorge",
  address: "Av. dos Automóveis, 1696",
  phone: "(11) 3456-7890",
  openingHours: "Seg - Dom: 7h às 22h",
  deliveryFee: 5.99,
  minOrderValue: 20,
  estimatedDeliveryTime: "30-45 min",
  rating: 4.8,
  logo: "/generic-supermarket-logo.png",
  banner: "/images/pagamentos.png",
}

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Padaria",
    icon: "🥖",
    image: "/bakery-bread-display.png",
  },
  {
    id: "2",
    name: "Hortifruti",
    icon: "🍓",
    image: "/fresh-strawberry.jpg",
  },
  {
    id: "3",
    name: "Açougue",
    icon: "🥩",
    image: "/meat-steak.jpg",
  },
  {
    id: "4",
    name: "Bebidas",
    icon: "🥤",
    image: "/beverages-drinks.jpg",
  },
  {
    id: "5",
    name: "Mercearia",
    icon: "🛒",
    image: "/busy-grocery-aisle.png",
  },
  {
    id: "6",
    name: "Pet Shop",
    icon: "🐕",
    image: "/pet-supplies.png",
  },
  {
    id: "7",
    name: "Limpeza",
    icon: "🧹",
    image: "/assorted-cleaning-supplies.png",
  },
  {
    id: "8",
    name: "Gourmet",
    icon: "🍷",
    image: "/gourmet-food-display.png",
  },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Pão Francês",
    description: "Pão francês fresquinho do dia",
    price: 0.5,
    image: "/french-bread.png",
    categoryId: "1",
    unit: "un",
    size: "60g",
    stock: 100,
    featured: true,
  },
  {
    id: "2",
    name: "Morango",
    description: "Morango fresco e selecionado",
    price: 8.99,
    originalPrice: 12.99,
    image: "/fresh-strawberries.png",
    categoryId: "2",
    unit: "kg",
    size: "500g",
    stock: 50,
    featured: true,
  },
  {
    id: "3",
    name: "Picanha",
    description: "Picanha premium de primeira qualidade",
    price: 69.99,
    image: "/picanha-meat.jpg",
    categoryId: "3",
    unit: "kg",
    size: "1kg",
    stock: 20,
    featured: true,
  },
  {
    id: "4",
    name: "Coca-Cola 2L",
    description: "Refrigerante Coca-Cola 2 litros",
    price: 9.99,
    originalPrice: 11.99,
    image: "/classic-coca-cola.png",
    categoryId: "4",
    unit: "un",
    size: "2L",
    stock: 80,
    featured: false,
  },
  {
    id: "5",
    name: "Arroz Branco 5kg",
    description: "Arroz tipo 1 de qualidade",
    price: 24.99,
    image: "/rice-bag.png",
    categoryId: "5",
    unit: "un",
    size: "5kg",
    stock: 60,
    featured: false,
  },
  {
    id: "6",
    name: "Ração Golden",
    description: "Ração premium para cães adultos",
    price: 159.99,
    image: "/dog-food-bag.jpg",
    categoryId: "6",
    unit: "un",
    size: "15kg",
    stock: 15,
    featured: false,
  },
]

export const mockUser: User = {
  id: "1",
  email: "cliente@email.com",
  name: "João Silva",
  phone: "(11) 98765-4321",
  role: "client",
  addresses: [
    {
      id: "1",
      street: "Rua das Flores",
      number: "123",
      complement: "Apto 45",
      neighborhood: "Centro",
      city: "São Paulo",
      state: "SP",
      zipCode: "01234-567",
      isDefault: true,
    },
  ],
  createdAt: new Date().toISOString(),
}

export const mockOrders: Order[] = [
  {
    id: "1",
    userId: "1",
    items: [
      {
        productId: "2",
        productName: "Morango",
        productImage: "/fresh-strawberries.png",
        quantity: 2,
        price: 8.99,
        subtotal: 17.98,
      },
      {
        productId: "4",
        productName: "Coca-Cola 2L",
        productImage: "/classic-coca-cola.png",
        quantity: 1,
        price: 9.99,
        subtotal: 9.99,
      },
    ],
    subtotal: 27.97,
    deliveryFee: 5.99,
    totalAmount: 33.96,
    status: "delivered",
    paymentMethod: "pix",
    deliveryAddress: mockUser.addresses[0],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
